server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: atv@@2303
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  config:
    import: optional:configserver:http://localhost:8086

#Configuration for actuator
management:
  health:
    cassandra:
      enabled: true
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#Configuration for Resilience
resilience4j:
  circuitbreaker:
    instances:
      User_rating_college_breaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      User_rating_college_retry:
        maxAttempts: 3
        waitDuration: 5s
  ratelimiter:
    instances:
      User_rating_college_rateLimiter:
        limitRefreshPeriod: 4s
        limitForPeriod: 2
        timeoutDuration: 2s
